### ISSUE TITLE
./build_openroad.sh fails while building with clang on Ubuntu 18.04

### ISSUE THREAD

**Issue by gkamendje** [The-OpenROAD-Project/OpenROAD-flow#119]
Hello,
I am running on Ubuntu 18.04 with both gcc and clang installed. 
```
-- OpenROAD version: 0.9.0
-- OpenROAD git sha: f1d2f22906ff3a0c9b4d420407c3d6d1e702fe33
-- System name: Linux
-- Compiler: Clang 6.0.0
-- Build type: RELEASE
```

running ./build_openroad.sh with clang as the default compiler fails with the following error. 

```
app/libOpenSTA.a(DispatchQueue.cc.o): undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```
I guess it is somehow related to the following config message. 
```
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
```
This is rather surprising given that I do have libpthread-stubs0-dev  (0.3-4) installed on my machine. Anyhow, in order to move forward, I  added the `-DCMAKE_CXX_FLAGS=-pthread` compiler option in the build script. This takes me to the next error message

```
....OpenDB/src/defout/libdefout.a OpenDB/src/lefout/liblefout.a -ltcl OpenDB/src/lefin/liblefin.a OpenDB/src/zutil/libzutil.a /home/tmp_compile/oproad-smic018-20200718/tools/OpenROAD/src/OpenDB/src/lef/lib/liblef.a FastRoute/third_party/fastroute/libFastRoute4.1.a flute3/libflute.a FastRoute/third_party/pdrev/libpdrev.a /usr/lib/x86_64-linux-gnu/libtcl.so -ldl OpenPhySyn/src/StandardTransforms/BufferFanoutTransform/libbuffer_fanout.a OpenPhySyn/src/StandardTransforms/GateCloningTransform/libgate_clone.a OpenPhySyn/src/StandardTransforms/PinSwapTransform/libpin_swap.a OpenPhySyn/src/StandardTransforms/ConstantPropagationTransform/libconstant_propagation.a /home/tmp_compile/oproad-smic018-20200718/tools/OpenROAD/src/OpenSTA/app/libOpenSTA.a
OpenPhySyn/libOpenPhySyn.a(FileUtils.cpp.o): In function `psn::FileUtils::createDirectory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
FileUtils.cpp:(.text+0x83): undefined reference to `std::filesystem::create_directory(std::filesystem::__cxx11::path const&)'
OpenPhySyn/libOpenPhySyn.a(FileUtils.cpp.o): In function `psn::FileUtils::readDirectory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
FileUtils.cpp:(.text+0x1ee): undefined reference to `std::filesystem::__cxx11::directory_iterator::directory_iterator(std::filesystem::__cxx11::path const&, std::filesystem::directory_options, std::error_code*)'
FileUtils.cpp:(.text+0x334): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'
FileUtils.cpp:(.text+0x42c): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator++()'
OpenPhySyn/libOpenPhySyn.a(FileUtils.cpp.o): In function `std::filesystem::__cxx11::path::path<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::filesystem::__cxx11::path>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::filesystem::__cxx11::path::format)':
FileUtils.cpp:(.text._ZNSt10filesystem7__cxx114pathC2INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES1_EERKT_NS1_6formatE[_ZNSt10filesystem7__cxx114pathC2INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES1_EERKT_NS1_6formatE]+0x9b): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
OpenPhySyn/libOpenPhySyn.a(FileUtils.cpp.o): In function `std::filesystem::__cxx11::path::operator/=(std::filesystem::__cxx11::path const&)':
FileUtils.cpp:(.text._ZNSt10filesystem7__cxx114pathdVERKS1_[_ZNSt10filesystem7__cxx114pathdVERKS1_]+0x18): undefined reference to `std::filesystem::__cxx11::path::has_root_directory() const'
FileUtils.cpp:(.text._ZNSt10filesystem7__cxx114pathdVERKS1_[_ZNSt10filesystem7__cxx114pathdVERKS1_]+0x31): undefined reference to `std::filesystem::__cxx11::path::has_filename() const'
FileUtils.cpp:(.text._ZNSt10filesystem7__cxx114pathdVERKS1_[_ZNSt10filesystem7__cxx114pathdVERKS1_]+0x188): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
src/CMakeFiles/openroad.dir/build.make:210: recipe for target 'src/openroad' failed
make[2]: *** [src/openroad] Error 1

```
I tried adding  `-DCMAKE_EXE_LINKER_FLAGS=-lstdc++fs`  and/or  `-DCMAKE_EXE_LINKER_FLAGS=-lc++fs`  to the build script without success. 
The only way I can get this to build is by switching to GCC with something like 

`-DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++`

Has anyone been able to successfully build with Clang 6.0 on Ubuntu?
